version: 2
common: &common
  working_directory: ~/threadbench
  steps:
    - checkout
    - run:
        name: install dependencies
        command: pip install tox codecov pre-commit --user
    - run:
        name: run tox
        command: ~/.local/bin/tox

jobs:
  "python-3.7":
    <<: *common
    docker:
      - image: lambgeo/lambda:gdal2.4-py3.7-geolayer
        environment:
          - TOXENV=py37

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - python-3.7